### ISSUE TITLE
Pull new css Jan 31

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#63]
@djsutter hey Duncan! Can you please pull the new custom.scss which includes updates to:

` <p>` line 725
https://github.com/loogart/impact-canada/commit/f63259b390b1295703f7c3b2e4a4bd65031c33b7

and to the new `.sts-selection` line 1051
https://github.com/loogart/impact-canada/commit/c06c6b835cfb806dfea464a01c637aac6ef83512

**Comment by djsutter** [comment]
This is done. In production now.

**Comment by loogart** [comment]
@djsutter hey, maybe i messed up - not sure. 
Between lines 782-794, I want the font-size to be 1.8rem (essentially smaller than 20px), I thought I managed that with the custom.scss (which should compile to custom.css). 

**Qualivera css**
```
section#staticContent p,
section#staticContent li,
section#staticContent a, section.basic-page--content p,
section.basic-page--content li,
section.basic-page--content a {
  font-weight: 400;
  font-style: normal;
  font-size: 1.8rem;
  line-height: 1.5;
  letter-spacing: .02em;
  color: rgba(0, 0, 0, 0.86);
  color: #10172D;
}
```
**Loogart css**
section#staticContent p, section#staticContent li, section#staticContent a {
    font-weight: 400;
    font-style: normal;
    font-size: 1.8rem;
    line-height: 1.5;
    letter-spacing: .02em;
    color: rgba(0, 0, 0, 0.86);
    color: #10172D;
}

**Comment by djsutter** [comment]
What's happening is that there are a fair number of differences between your scss and my scss. It's mostly due to changes I've had to make that are specific to the templates in Drupal; a problem that you don't have on your site. I try to pick up changes by looking at your commits, but it's not foolproof as we see.
Any suggestions how we can resolve this? Ideally, I suppose, you would be able to change the exact scss & css that goes into the dev site. But we best do it through github to manage the workflow.
Would you like me to dump my scss into your project? Can I? Then you can compare the two.
Maybe it's time to give you access to the Drupal theme in github. We could try it and see how it works.
I also don't mind giving you either ftp access or even shell access to the server. But it's linux, so maybe more than you want.
We can discuss by phone if easier.

**Comment by djsutter** [comment]
Re github access to the theme - this might resolve the other issue of your custom css.
As long as we get things looking good on the dev site, I can do git pulls in production any time. As long as we're pretty confident. Then again, can always revert.

**Comment by loogart** [comment]
@djsutter yes. How about we create a new github branch and I get access to the Drupal theme in github. I am game to try it both ways to see what works best for us!

I would like gettting the ftp access (i assume I can't use a GUI for our purposes such as Filezilla?)

How about I call you this pm (just finishing up a rush project right now!)

**Comment by djsutter** [comment]
I made the small change and pulled it on both the dev and prod sites. This is a good example of differences between yours and mine. Mine doesn't have a #staticContent anywhere. Perhaps it should, but these things can get lost with the complexity of templating in Drupal.

**Comment by djsutter** [comment]
BTW, sent an invitation for you to join the pco-bcp group and you can make changes to the theme "impact_bootstrap"

**Comment by djsutter** [comment]
Also BTW, I can give you ftp access through Filezilla. But I think I will move it to a different vhost this weekend, because it's currently co-located with my own corp stuff. Will give you the access details when it's ready.

**Comment by loogart** [comment]
awesome thanks Duncan!

**Comment by loogart** [comment]
@djsutter excellent, i see the Sass folder and will explore. So i assume I can commit any css changes to that file and you will then test on qualivera prior to pushing to live?

**Comment by djsutter** [comment]
@loogart Yes you should be able to commit changes to scss and potentially other files. The only complication I can think of right now is that the scss needs to be compiled, and normally we commit both the scss and the css together. But I can do the compile and commit the css.
