### ISSUE TITLE
URGENT: Challenge subpages not showing up

### ISSUE THREAD

**Issue by loogart** [loogart/impact-canada#71]
Hey @djsutter for some reason, we are getting an error on all subpages for all challenges:

![screen shot 2019-02-13 at 9 00 26 am](https://user-images.githubusercontent.com/7881400/52717171-79ed1780-2f6e-11e9-925b-7459d8c9d788.png)

The challenge is launching at noon! Can you help us out asap.
If it is related to the challenge details title, no worries, i will revert back to js for this challenge.

**Comment by djsutter** [comment]
Should be fixed now. During the rush to get this out, I was trying to bullet-proof the code so that it would be tolerant of a field that did not exist. Couldn't get that working so I went ahead with the software update knowing that I had just created the field. But forgot to remove test field name from the subpage code.

**Comment by loogart** [comment]
perfect thanks D! Please disregard my email about this issue. I sent it 5 minutes after you fixed this!
